export const eventData = [
    {
        id: '1',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'Web Kode 23',
        para: 'The automated pre process starts as soon as your clothes go into the machine. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.',
        loc: 'NED-UET',
        eventDate: '20 jun 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'previous',
    },
    {
        id: '2',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'Web Kode 23',
        para: 'The automated pre process starts as soon as your clothes go into the machine. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.',
        loc: 'NED-UET',
        eventDate: '20 jun 2023',
        direction: 'row-reverse',
        imgClass: "event_card_sec_reverse_img",
        eventMode: 'previous',
    },
    {
        id: '3',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'Web Kode 23',
        para: 'The automated present process starts as soon as your clothes go into the machine. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.',
        loc: 'NED-UET',
        eventDate: '20 jun 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'present',
    },
    {
        id: '4',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'Web Kode 23',
        para: 'The automated present process starts as soon as your clothes go into the machine. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.',
        loc: 'NED-UET',
        eventDate: '20 jun 2023',
        direction: 'row-reverse',
        imgClass: "event_card_sec_reverse_img",
        eventMode: 'present',
    },
    {
        id: '5',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'Web Kode 23',
        para: 'The automated present process starts as soon as your clothes go into the machine. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.',
        loc: 'NED-UET',
        eventDate: '20 jun 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'present',
    },
    {
        id: '6',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'Web Kode 23',
        para: 'The automated upcoming process starts as soon as your clothes go into the machine. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.',
        loc: 'NED-UET',
        eventDate: '20 jun 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'upcoming',
    },
    {
        id: '7',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'Web Kode 23',
        para: 'The automated upcoming process starts as soon as your clothes go into the machine. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet.',
        loc: 'NED-UET',
        eventDate: '20 jun 2023',
        direction: 'row-reverse',
        imgClass: "event_card_sec_reverse_img",
        eventMode: 'upcoming',
    },
]