export const eventData = [
    {
        id: '1',
        imgFirst: './images/present-event-img2.jpg',
        imgSecond: './images/present-event-small-img2.jpeg',
        heading: 'CodersCombat23',
        para: 'This event is all about testing and improving coding skills in a competitive environment. CodersCombat2020 is a coding competition that challenges participants to solve complex coding problems under pressure. Participants will have a limited amount of time to solve as many problems as they can, and the top performers will win prizes and recognition.',
        loc: 'NED-UET',
        eventDate: '25 march 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'previous',
    },
    {
        id: '2',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'CodeForces',
        para: 'CodeForces is a popular competitive programming platform that hosts regular contests that are open to participants from all over the world, including Pakistan. Code Forces is the perfect opportunity for coders who thrive on challenges and want to test their coding abilities against their peers.',
        loc: 'FAST NUCES',
        eventDate: '15 march 2023',
        direction: 'row-reverse',
        imgClass: "event_card_sec_reverse_img",
        eventMode: 'previous',
    },
    {
        id: '3',
        imgFirst: 'https://preview.colorlib.com/theme/eventz/assets/img/gallery/about1.png',
        imgSecond: './images/event-sm.jpeg',
        heading: 'WebKode2023',
        para: 'This event is all about web development and coding. Participants will learn the latest techniques and tools for building modern web applications, from frontend frameworks to backend servers. WebKode2023 is the perfect opportunity for developers of all levels to enhance their skills, connect with peers, and stay up-to-date with the latest trends in web development.',
        loc: 'NED-UET Main Auditorium',
        eventDate: '28 april 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'present',
    },
    {
        id: '4',
        imgFirst: './images/present-event-img2.jpg',
        imgSecond: './images/present-event-small-img2.jpeg',
        heading: 'CodingGuru2023',
        para: 'This event is designed for advanced coders who want to take their skills to the next level. CodingGuru2022 brings together top developers from around the university to share their expertise and insights on the latest coding practices, algorithms, and software engineering principles.',
        loc: 'NED-UET Civil AV Hall',
        eventDate: '27 april 2023',
        direction: 'row-reverse',
        imgClass: "event_card_sec_reverse_img",
        eventMode: 'present',
    },
    {
        id: '5',
        imgFirst: './images/blog-2.png',
        imgSecond: './images/present-event-small-img3.jpeg',
        heading: 'EliteCoders',
        para: 'This exciting event is exclusively for the university elite coders who want to take their skills to the next level and showcase their expertise. It offers a unique opportunity for participants to engage in a variety of coding challenges, hackathons, and collaborative projects.',
        loc: 'UIT Main Auditorium',
        eventDate: '25 april 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'present',
    },
    {
        id: '6',
        imgFirst: './images/present-event-img2.jpg',
        imgSecond: './images/present-event-small-img2.jpeg',
        heading: 'Google DSC Solution Task',
        para: 'This is a global competition that invites students to develop solutions using Google technology. Pakistani students can participate in this challenge as well.',
        loc: 'NED-UET Main Auditorium',
        eventDate: '15 june 2023',
        direction: 'row',
        imgClass: "event_card_sec_row_img",
        eventMode: 'upcoming',
    },
    {
        id: '7',
        imgFirst: './images/ongoing-event-img3.jfif',
        imgSecond: './images/event-sm.jpeg',
        heading: 'CodeChef',
        para: ' CodeChef is one of the largest coding platforms in Pakistan, hosting monthly coding contests, online courses, and a community of coders from around the world.',
        loc: 'Sir Syed University',
        eventDate: '20 july 2023',
        direction: 'row-reverse',
        imgClass: "event_card_sec_reverse_img",
        eventMode: 'upcoming',
    },
]